---
- name: Set up environment for Sentinel API
  hosts: sentinel
  become: true
  gather_facts: False
  tasks:
    - name: Loading tasks
      wait_for:
        timeout: 10
    - name: Install Git
      command: yum install git -y
    - name: Copy ssh key
      copy:
        src: ~/.ssh/ssh-kp.pem
        dest: /home/ec2-user/.ssh/ssh-kp.pem
    - name: Acquire Auth
      copy:
        src: ~/.sentinel/config/token.txt
        dest: /home/ec2-user/
    - name: Install gcc
      command: sudo yum install -y gcc-c++ make
    - name: Get node source
      shell: curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
      register: result
    - name: Install node
      command: sudo yum install -y nodejs
    - name: Git clone the repository
      retries: 3
      git:
        repo: https://github.com/Sentinel-PaaS/sentinel-api-2.git
        dest: /home/ec2-user/sentinel-api-2
        clone: yes
    - name: Install pm2
      npm:
        name: pm2
        global: yes
    - name: Install Sentinel API dependencies
      command: npm install
      args:
        chdir: /home/ec2-user/sentinel-api-2/
    - name: Start API server
      command: pm2 start "npm start" --name "Sentinel API"
      args:
        chdir: /home/ec2-user/sentinel-api-2/
- name: Install nginx
  hosts: sentinel
  become: true
  gather_facts: false
  tasks:
    - name: Update yum utils
      command: yum install yum-utils
    - name: Get nginx repo file
      get_url:
        url: https://raw.githubusercontent.com/Sentinel-PaaS/cli-configs/main/nginx.repo
        dest: /etc/yum.repos.d/nginx.repo
    - name: Install nginx
      command: yum install nginx -y
    - name: Get nginx conf file
      get_url:
        url: https://raw.githubusercontent.com/Sentinel-PaaS/cli-configs/main/default.conf
        dest: /etc/nginx/conf.d/default.conf
    - name: start nginx
      command: systemctl start nginx
    - name: Loading nginx 
      wait_for:
        timeout: 10